config/routes.rb
Rails.application.routes.draw do
  get '/'=>'practice#index'
  post '/'=>'practice#index'
  resources :apples
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/apple.rb
class Apple < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController
  def index
    @apples = Apple.all
  end

  def new
  @apples = Apple.new
  respond_to do |format|
    format.html
    format.js
  end
end

def create
  @apples = Apple.all
  @apple = Apple.new(apple_params)
  respond_to do |format|
    if @apple.save
      format.html
      format.js
    else
      format.js {render :new}
    end
  end
end

def apple_params
  params.require(:apple).permit(:name)
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/practice_controller.rb
class PracticeController < ApplicationController
  def index
    @title = params[:title]
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/apples_helper.rb
module ApplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/practice_helper.rb
module PracticeHelper
end

app/views/apples/_apple.html.erb
<tr>
<td>
  <%= apple.name %>
</td>
</tr>

app/views/apples/_form.html.erb
<%= simple_form_for @apples, remote: true do |f| %>
  <%= f.input :name %>
  <%= f.button :submit ,"追加" %>
<% end %>

app/views/apples/_index.html.erb
<%= render @apples %>

app/views/apples/create.js.erb
$('#apples').html("<%= j (render 'index') %>");
$('#apple-form').fadeOut(600);

app/views/apples/index.html.erb
<h1>Appleモデル一覧</h1>
<table class="table" id="apples">
  <%= render @apples %>
</table>
<%= link_to "データを追加する", new_apple_path, remote: true %>
<div id="apple-form"></div>

app/views/apples/new.js.erb
$('#apple-form').html("<%= j (render 'form') %>");
$('#apple-form').fadeIn(800);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AjaxStudy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/practice/index.html.erb
<h1>Ajaxを使ってみよう</h1>
<%= form_tag(url_for(:action => 'index'), :remote => true) do %>
  <%= text_field_tag :title %>
  <%= submit_tag "タイトルを変更する" %>
<% end %>

app/views/practice/index.js.erb
console.log("hoge");
  $("h1").html("<%=@title%>");